### ISSUE TITLE
Update Springer Nature color palette

### ISSUE THREAD

**Issue by foxintherain** [springernature/frontend-toolkits#531]
<h2>Introduce new color palette:</h2>
<div class="table-wrap">

**Note: these colors are within the "Accent" and "Corporate" colors category**

Old colors | New colors
-- | --
"Grey Blue Dark" #183642 | "Universal Dark Blue" #01324b
"Grey Blue Mid 1" #486a7e | REMOVE
"Grey Blue Mid 3" #8faec1 | REMOVE
**No existing color** | "Grey Blue Light 1" ebf1f5
"Grey Blue Light" #cedbe0 | "Grey Blue Light 2" #cedbe0
"Bright Blue" #3c9cd7 | "Research Blue" #0070a8
"Lilac" #9d7eb8 | "Research Purple" #785ba7
"Emerald" #00b8b0 | "Research Forest" #007373
"Orange" #f58220 | "Orange" #c75301
"Lime" #b6bd04 | "Research Red" #be1818

</div>

<h2>Context</h2>

 **Springer Nature will be refreshing its visual identity**

- I’ve been working with Matt Harvey and his team to agree on a new color palette for digital that is more accessible 
- The new palette will be rolled out over time with no fixed deadline - for RP, we’re still in alpha/beta phase so I think there is less pressure
- I’ve been creating a  [color accessibility guide](https://docs.google.com/document/d/10XVU0kioJB1b3l2OkKXDF7AX2DqCzbq1tMNdN2RLyco/edit#)  that can be used for teams in SND, Marketing and Brand - this will eventually live in elements

**Comment by alexkilgour** [comment]
Work doen in #530
