### ISSUE TITLE
Nature Footer Improvements

### ISSUE THREAD

**Issue by alexkilgour** [springernature/frontend-toolkits#668]
Some improvements need to be made to the nature footer component:
- Can we remove the dependency on utility classes?
- Check that the template is up to date from Oscar
- Relies on `global-menu` component
- Icons are duplicated from `brand-context` how do we solve this? (same for other components)
- Template also links to image stored in component, how do apps resolve this?

**Comment by benjclark** [comment]
https://github.com/springernature/frontend-toolkits/pull/753

Can we remove the dependency on utility classes? ✅ 
Check that the template is up to date from Oscar ✅ 
Relies on global-menu component ✅ 
Icons are duplicated from brand-context how do we solve this? (same for other components) ❌ 
Template also links to image stored in component, how do apps resolve this? ❌

**Comment by benjclark** [comment]
@alexkilgour now that Global Footer has been published I believe we can close this issue now. The remaining points above with red crosses have been addressed I believe, as icon paths are provided to the view templates in the data as img src paths
