### ISSUE TITLE
using `index.hbs` as the filename for the handlebars file in the view folder.

### ISSUE THREAD

**Issue by sturobson** [springernature/frontend-toolkits#722]
Whilst working through some things I spotted that on the [global card](https://elements.public.springernature.app/springer/components/global-card) page the handlebars that is displayed in the code is from the [demo](https://github.com/springernature/frontend-toolkits/tree/master/toolkits/global/packages/global-card/demo) and not the [view] folder. 

It [transpires](https://github.com/springernature/frontend-design-system/issues/149) that this is because of the `global-` prefix on the handlebars file. 

I cannot find documentation explaining what the filename should be. 

I think, going forward we should look to use `index.hbs` as the file name in the `view` folder.

This can then be assigned an appropriate name in the application/site using it: 

```
"dynamicPartials": {
	"hero": "./toolkits/springer/packages/springer-hero/view/index.hbs"
}
```

We should still look to document this (although we could add the creation of `/view/index.hbs` as part of the [pattern generator](https://github.com/springernature/frontend-package-manager) to save any need for looking (which might also help developers checklists when creating a component in the toolkits)). 

In the mean time, @sangitamane is [working on a solution](https://github.com/springernature/frontend-design-system/issues/149#issuecomment-1088511202) to check for the prefix on filenames in the `view` folder.

**Comment by alexkilgour** [comment]
Just quickly looking at that issue - I agree this would be better in 99% of cases, but we also will have _some_ cases e.g. the global-forms, where there is more than one template, so would need to agree on how to handle those cases

**Comment by alexkilgour** [comment]
> We should still look to document this
I am in the middle of this at the moment!

**Comment by sturobson** [comment]
making a note of this for the single release / elements codebase so closing now.
