### ISSUE TITLE
CHORE: check and update components brand-context versions

### ISSUE THREAD

**Issue by sturobson** [springernature/frontend-toolkits#778]
@Heydon spotted an issue with the demo for the springer header on the elements site that was not reflected in their project.

It turns out, (there's a little assuming going on here), that the demos created for the Elements site pick up the relevant `brand-context` that is defined in the components own `package.json` file.

This led to the demo on the Elements site using 'pre font fixing' Sass which lead to `1rem` == `10px` rather than the current `1rem` == `16px`.

As the demo of a component is becoming more integrated into the Elements site, with newer demos being added we need to check and fix the `brand-context` that is being used in the components `package.json` file so that what we see in the demo is a true reflection of what the component should look like (if you like to keep your projects updated to latest). 

I've compiled [a quick spreadsheet of all the components](https://docs.google.com/spreadsheets/d/1bmCDNUDijgt7sJmlK8UUusIINRllFy4aGrrMOP2jyHM/edit#gid=0) listing out the brand-context that is being defined.

This kind of thing could become less of a hassle if we move to single release for the entirety of toolkits or rework how demos get made for elements.

todo:

- [ ] investigate which components have demos that are used in the Elements Design System site
- [ ] update version to latest
- [ ] investigate how this could become unnecessary for creating demos

**Comment by Heydon** [comment]
+1 I keep getting tripped up by this. I think most components can simply be upgraded to the latest brand context.

**Comment by Heydon** [comment]
Here's the PR: https://github.com/springernature/frontend-toolkits/pull/779
