### ISSUE TITLE
Demo brand-context tokens incompatibility.

### ISSUE THREAD

**Issue by Heydon** [springernature/frontend-toolkits#793]
### What

When trying to run demos for packages, I get an error **00-tokens** can't be found (in the brand-context style imports).

The error is:

```
✖ fail sass could not compile sass to css
  Error: Unhandled rejection: Can't find stylesheet to import.
    ╷
  8 │ @import '00-tokens/';
    │         ^^^^^^^^^^^^
    ╵
    node_modules/@springernature/brand-context/default/scss/abstracts.scss 8:9    @import
    ../node_modules/@springernature/brand-context/default/scss/enhanced.scss 6:9  @import
    - 2:9
```

This is occurring with the global-status-message package, even though it is on brand-context version 25?

### Why

Not sure. And not sure if this affects just demos or production code at this stage. It is something that cropped up when @StuRobson and I were trying to get tokens working with the **global-forms** component. But I don't recall what caused or fixed it.

### Done when

[ ] Running any package demo or production Sass stack does not result in this error.

**Comment by sturobson** [comment]
We've found this was an issue with `node_modules` locally … rimraf'ing the `node_modules` folder and trying again fixed it.
