### ISSUE TITLE
Write explanation of layout primitives forAlex to review

### ISSUE THREAD

**Issue by Heydon** [springernature/frontend-toolkits#859]
- [x] Draft the section (see https://gist.github.com/Heydon/c65c0aa1ca0fccbb30e7cb1b4a499063)
- [x] Review by Alex
- [x] Amend

**Comment by Heydon** [comment]
@alexhallspringer Ready for first review now 🙂

**Comment by alexhallspringer** [comment]
Reviewing now. I've moved what you drafted into the layout google doc just so I can edit. Hopefully that's alright.
