### ISSUE TITLE
javascript helpers in global-context

### ISSUE THREAD

**Issue by alexkilgour** [springernature/frontend-toolkits#86]
if you are using, for example, `global-expander` which is all javascript there is no need for branded versions of that component, you can use the global directly. If that component uses js helper classes from `global-context` then it means you need to have both `global-context` and `brand-context` in your app dependencies (for CSS you should only be using a branded context file)

as this is the case does it makes sense to remove the js helpers from context and put them in their own component - `global-js-helpers`?

**Comment by davidpauljunior** [comment]
JS will be moved into a separate package.
